---

- name: Include per distro vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Include per distro tasks
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Generate secret key
  set_fact:
      grafana_secret: "{{999999999999999999999 | random | to_uuid | hash('md5')}}"

- name: Ensure directories
  file:
    path: "{{ item }}"
    owner: grafana
    group: grafana
    mode: 0644
    state: directory
  with_items:
      "{{ grafana_paths.values() }}"

- name: Configure
  template:
    src: "grafana.ini.j2"
    dest: "{{ grafana_paths['conf'] | realpath }}/grafana.ini"
    owner: grafana
    group: grafana
    mode:  0644
  notify: restart grafana

- name: Overwrite systemd unit
  template:
    src: "grafana-server.service.j2"
    dest: "/usr/lib/systemd/system/grafana-server.service"
    owner: root
    group: root
    mode:  0644
  notify: restart grafana

- name: Reload daemon
  systemd: daemon_reload=yes
  when: ansible_virtualization_type != 'docker'

- name: Provision - datasources
  template:
    src: "prometheus.yaml.j2"
    dest: "{{ grafana_paths['datasources'] | realpath }}/prometheus.yaml"
    owner: grafana
    group: grafana
    mode:  0644
  notify: restart grafana

- name: Provision - dashboards
  copy:
    src: "{{item}}.json"
    dest: "{{ grafana_paths['dashboards'] | realpath }}/{{item}}.json"
    owner: grafana
    group: grafana
    mode:  0644
    backup: yes
  with_items: grafana_dashboards
  notify: restart grafana

- name: Provision - dashboard config
  template:
    src: "openio.yml.j2"
    dest: "{{ grafana_paths['dashboards'] | realpath }}/openio.yml"
    owner: grafana
    group: grafana
    mode:  0644
  notify: restart grafana

- name: Start service
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: true
